import { useEffect, useSyncExternalStore } from "react";
import { isAddress, type Address } from "viem";

/**
 * Bundled token metadata lives in `tokens/<chainId>.json` next to the app,
 * generated by scripts/sync-default-tokens.ts, and is fetched from the app's
 * own origin the first time a chain needs it. Keeping it out of the script
 * bundle keeps startup fast; nothing is downloaded from any other service.
 */
export type BundledToken = {
  address: Address;
  symbol: string;
  name: string;
  decimals: number;
};

const catalog = new Map<number, BundledToken[]>();
const pending = new Map<number, Promise<void>>();
const listeners = new Set<() => void>();
let version = 0;

function notify() {
  version++;
  for (const listener of listeners) listener();
}

export function bundledTokens(chainId: number) {
  return catalog.get(chainId);
}

export function tokenCatalogLoaded(chainId: number) {
  return catalog.has(chainId);
}

/** Installs a chain's list directly; used by tests and the sync script. */
export function primeTokenCatalog(chainId: number, tokens: BundledToken[]) {
  catalog.set(chainId, validateTokens(tokens));
  notify();
}

function validateTokens(input: unknown): BundledToken[] {
  if (!Array.isArray(input)) throw new Error("Invalid token catalog.");
  return input.filter(
    (token): token is BundledToken =>
      !!token &&
      typeof token === "object" &&
      isAddress(token.address, { strict: false }) &&
      typeof token.symbol === "string" &&
      typeof token.name === "string" &&
      Number.isInteger(token.decimals) &&
      token.decimals >= 0 &&
      token.decimals <= 255,
  );
}

export function tokenCatalogUrl(chainId: number) {
  return new URL(`tokens/${chainId}.json`, document.baseURI);
}

export function loadTokenCatalog(chainId: number): Promise<void> {
  if (catalog.has(chainId) || typeof document === "undefined")
    return Promise.resolve();
  const existing = pending.get(chainId);
  if (existing) return existing;
  // A chain without a file yields 404 from the launcher, or the index page
  // from SPA-style hosts; both mean "no bundled tokens", never a stuck page.
  const request = fetch(tokenCatalogUrl(chainId), { redirect: "error" })
    .then(async (response) => {
      const type = response.headers.get("content-type") ?? "";
      if (!response.ok || !type.includes("json")) return [];
      return validateTokens(await response.json());
    })
    .catch((error: unknown): BundledToken[] => {
      console.warn(`Token catalog for chain ${chainId} unavailable.`, error);
      return [];
    })
    .then((tokens) => {
      catalog.set(chainId, tokens);
      notify();
    })
    .finally(() => pending.delete(chainId));
  pending.set(chainId, request);
  return request;
}

function subscribe(listener: () => void) {
  listeners.add(listener);
  return () => {
    listeners.delete(listener);
  };
}

/** Re-renders when any catalog arrives and returns whether this chain's is ready. */
export function useTokenCatalog(chainId: number) {
  useSyncExternalStore(
    subscribe,
    () => version,
    () => version,
  );
  useEffect(() => {
    void loadTokenCatalog(chainId);
  }, [chainId]);
  return catalog.has(chainId);
}
